### ISSUE TITLE
Cut a new version

### ISSUE THREAD

**Issue by guibou** [guibou/krank#19]
Thanks to @gbataille, we now have a working minimal project. I even ran krank an a huge codebase of 857K lines of code and got results!

We are close to a release, but I think that the following point may be fixed before:

- [x] #15, which makes batch run difficult
- [x] #16 , need context for errors
- [x] #17 and #18 need authenticated requests.
- [x] More tests. We have code test, but no CLI / behavior tests.
- [ ] Clean the `README.md` file.

**Comment by guibou** [comment]
cc @gbataille for notifications.

**Comment by gbataille** [comment]
@guibou 
Let's maybe not hold the first release on the lack of tests? Maybe we could get some exposure to the tool.
Tests should be the next priority but the tool is small enough, straightforward enough for the moment that we should release without I think

**Comment by guibou** [comment]
Agree. @gbataille could you check #28, #29 which are the blockers for a release. #28 simplifies the README, I'd like the readme to be as simple as possible and #29 removes the draft of gitlab support.

**Comment by guibou** [comment]
Done. Version `0.1.0` is now on hackage.

http://hackage.haskell.org/package/krank

Thanks for everyone involved (Cheers @gbataille ;)
